### ISSUE TITLE
Sub domain response 500 error

### ISSUE THREAD

**Issue by Mayandev** [neat-run/wrapped#11]
Nice project!

But I got 500 error with sub-domain when I click the share button.

**Comment by tedspare** [comment]
Thanks Mayan!

I've seen this for a few other users. Could you please share your link or a screenshot of the error? Let's get to the root cause.

**Comment by Mayandev** [comment]
> Thanks Mayan!
> 
> 
> 
> I've seen this for a few other users. Could you please share your link or a screenshot of the error? Let's get to the root cause.

https://Mayandev.wrapped.run

**Comment by Mayandev** [comment]
> > Thanks Mayan!
> > 
> > 
> > 
> > I've seen this for a few other users. Could you please share your link or a screenshot of the error? Let's get to the root cause.
> 
> https://Mayandev.wrapped.run

I can't find any relevant information here.

Will it be related to private repo?

**Comment by awareness481** [comment]
My guess would be that `getRow` here throws an error. When there's an error thrown in `getServerSideProps` you'll get a 500.
https://github.com/neat-run/wrapped/blob/bc60f605499c2a057d29e2a02b30009caad61e06/utils/exports.ts#L104

So if the above is correct you'd have to find out why `getRow` is throwing an error.

**Comment by tedspare** [comment]
I think you're right Jesse. I was able to replicate the error locally and isolated it to `getRow`. Working on a fix.
