### ISSUE TITLE
No branding on downloaded image

### ISSUE THREAD

**Issue by apgapg** [neat-run/wrapped#14]
![wrapped (2)](https://user-images.githubusercontent.com/13887407/146631894-14374432-89b1-4921-89aa-4479a4c1b2ed.png)

It is good if we include something like `Generated using Github Wrapped` or so. 
If people post on social media there is no way to depict from where this image was generated.

**Comment by tedspare** [comment]
Thanks for the idea, Ayush. I've added a link to `Wrapped.run` at bottom-right. Please let me know if it's hard to read.

Also nice commit numbers 🚀

**Comment by apgapg** [comment]
Looks great now. Thanks for adding the same.
Closing issue
