### ISSUE TITLE
Private Git Repository

### ISSUE THREAD

**Issue by we452366** [neat-run/wrapped#17]
Hi, firstly, it's a amazing fabulous project! secondly, I want to know whether we can get data when the repository is not Github, thank you!

**Comment by tedspare** [comment]
Thanks for the kind words, Victor!

The project does pull from private repositories, unless an organization requires explicit access:
<img src="https://user-images.githubusercontent.com/36117635/147021263-afcb869c-a3b3-42a0-ac0b-8bd599035cad.png" width="500" />

We don't plan to support GitLab or BitBucket soon. Maybe next year!

Does this answer your question?

**Comment by we452366** [comment]
> Thanks for the kind words, Victor!
> 
> The project does pull from private repositories, unless an organization requires explicit access: <img alt="" width="500" src="https://user-images.githubusercontent.com/36117635/147021263-afcb869c-a3b3-42a0-ac0b-8bd599035cad.png">
> 
> We don't plan to support GitLab or BitBucket soon. Maybe next year!
> 
> Does this answer your question?

ok，got it, and thanks a lot
