### ISSUE TITLE
The Contributions count is not getting updated

### ISSUE THREAD

**Issue by ngsanthosh** [neat-run/wrapped#18]
The Contributions count is not getting updated, Like I show my data 1 week ago, now I have done my new 20-30 contributions., but now if I see the stats, still it is in the old contributions count. 

Please fix it.

**Comment by tedspare** [comment]
Thanks, Santhosh. You can get fresh stats by signing out (press `s` then refresh) and signing in again. Or in incognito.

Pull requests welcome.

**Comment by Saransh-cpp** [comment]
> You can get fresh stats by signing out (press `s` then refresh) and signing in again. Or in incognito.

Weirdly, this doesn't update the contribution overview and the contribution graph section. It does update every other section. Any solutions?

**Comment by ngsanthosh** [comment]
Please anybody from the team, fix this,....Else this Application is meaningless.

**Comment by Saransh-cpp** [comment]
> Else this Application is meaningless.

That was a bit harsh. I think this is a bug.

**Comment by ngsanthosh** [comment]
Sorry to say that but yeah..this is how a user's mindset will be if a application he/she trusts behave wrong

**Comment by tedspare** [comment]
> Weirdly, this doesn't update the contribution overview and the contribution graph section. It does update every other section. Any solutions?

Thanks for clarifying this, Saransh. I'll look into why some stats don't re-render.

Santhosh, thanks for the candid feedback. If you find it meaningless, you don't have to use it. It's a side project rather than an ongoing service.
