### ISSUE TITLE
Contribution is not updated

### ISSUE THREAD

**Issue by JohnDominicJasmin** [neat-run/wrapped#19]
I'm done signing in as incognito and refreshing the page multiple times but still not updating my recent contributions

**Comment by tedspare** [comment]
Hi John! Sorry for the late reply. This might be an issue with the way Apollo caches API request results. If you're still interested, could you try signing out and in again?

**Comment by ufukbakan** [comment]
I've more than 400 commits contribition graph shows only 30
Re-logged in nothing changed. Although i'm first time using this app how can it be cached? 
![wrapped_ufukbakan (1)](https://user-images.githubusercontent.com/44516872/209285016-acc8ea29-f751-4b69-bbf2-5358290b3328.png)

**Comment by bhuvansingla** [comment]
Looking at the code, quite a few GitHub queries are using values from 2021. This is why the data is not consistent.
https://github.com/neat-run/wrapped/blob/91ab99a527e593769fb06762e02f83e33f62d27e/utils/constants.js#L12-L15

**Comment by ufukbakan** [comment]
@tedspare update your static dates with dynamic last year...

**Comment by bhuvansingla** [comment]
@tedspare, this is a really cool tool. Do you think it can be updated for 2022? I have opened a quick PR for the same: https://github.com/neat-run/wrapped/pull/29.

**Comment by tedspare** [comment]
Thanks @bhuvansingla for closing this! Was AFK for a while.
