### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by Y-Less** [neat-run/wrapped#4]
I clicked the button on wrapped.run, granted oauth access, and nothing happened.  Tried it a few times before noticing that the address bar had changed to:

`https://wrapped.run/?error=server_error&error_description=Error+sending+confirmation+mail`

No actual indication of an error on the page, and I never provided an e-mail address to send a confirmation to (I just assumed it showed the stats in the browser).  Why would you even need a confirmation e-mail given that you connect to an existing github account?

**Comment by tedspare** [comment]
Thanks for noticing this! You're right that the site doesn't mention a confirmation email. It seems like a problem in GitHub auth or Supabase auth.

I'll look into a fix and, in the meantime, could you please
- go to your GitHub settings,
- go to Email,
- if there's an option to `Resend verification email`, click that,
- authorize the app again, and
- see if your stats show up?

Full instructions [here](https://docs.github.com/en/get-started/signing-up-for-github/verifying-your-email-address#verifying-your-email-address).
