### ISSUE TITLE
Delete profile

### ISSUE THREAD

**Issue by umegbewe** [neat-run/wrapped#9]
I think there should be an option for deleting profile, wasn't comfortable with the idea of my private commit being displayed, revoked wrapped access on Github but my profile link is still active.

**Comment by tedspare** [comment]
Thanks Umegbewe. Sorry to hear that made you uncomfortable. I'll add this unless you'd like to open a PR for it.

In the meantime, in the modal that showed before publishing your data, was the message clear? If not, I'll clarify this.

<img width="542" alt="Screen Shot 2021-12-16 at 9 42 05 AM" src="https://user-images.githubusercontent.com/36117635/146392544-7f8e69be-0722-4e42-8f62-d5cd4eea64f4.png">

**Comment by umegbewe** [comment]
Message is pretty clear, and what an amazing app btw.
Apprehended that there would be an option to revoke display of private commits before confirming the modal, that wasn't the case and the reason this issue is here.

**Comment by tedspare** [comment]
Okay so we'll add an option to un-publish your data. In the meantime, you can hover and click `Hide` on the stats you'd like to hide, then re-publish. They'll be removed I believe.

**Comment by sarimrmalik** [comment]
Yeap, hiding a stat will automatically remove the value from the database and also remove it from the link (if you've already created one). No need to re-publish. 

Re-publishing will add this information back to the database. This could probably be improved.

**Comment by umegbewe** [comment]
Issue resolved, Thanks much.
